# Generated by Django 5.0.6 on 2026-10-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('kitchens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchens.cloudkitchen'),
        ),
    ]
