# Generated by Django 5.0.6 on 2026-10-03 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudKitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('service_radius_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=4)),
                ('hygiene_score', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_veg', models.BooleanField(default=True)),
                ('accepts_non_veg', models.BooleanField(default=False)),
                ('accepts_jain', models.BooleanField(default=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=4)),
                ('max_daily_capacity', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Monday ... 6=Sunday')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='kitchens.cloudkitchen')),
            ],
        ),
    ]
