# Generated by Django 5.0.6 on 2026-10-10 12:36

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchens', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastCallDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('item_name', models.CharField(max_length=200)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.PositiveSmallIntegerField(default=25)),
                ('portions_total', models.PositiveIntegerField()),
                ('portions_left', models.PositiveIntegerField()),
                ('start_time', models.TimeField(default=datetime.time(12, 0))),
                ('end_time', models.TimeField(default=datetime.time(21, 0))),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='kitchens.cloudkitchen')),
            ],
            options={
                'unique_together': {('kitchen', 'deal_date', 'meal_type')},
            },
        ),
    ]
